### ISSUE TITLE
Allow for Lines

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/MapWalk#11]
Users will likely draw in 2 ways:
- Encircling an area (as we now allow)
- tracing a street (new)

If a user draws a straight line, ideally we would save that as a line, but with a 2x fatter pen width. Also: any way to actually "snap" to the underlying nearest road (so that the line is straight and follows the road)?

**Comment by tedbarnett** [comment]
![image](https://github.com/tedbarnett/MapWalk/assets/694013/0023a161-e40f-4f5d-b1c6-3ce688e54f61)

**Comment by bhautikpatoliya004** [comment]
@tedbarnett 
"any way to actually "snap" to the underlying nearest road (so that the line is straight and follows the road)?"
==> It's hard to find the road where the user is drawing and also need to check regarding straight line that follows the road.

**Comment by tedbarnett** [comment]
Works well enough for now!
