### ISSUE TITLE
Clearer indication of Drawing mode

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/MapWalk#12]
To make it more obvious that the user is in drawing mode, and not in "move mode" (map-moving-and-scaling), when the user taps a pen to draw...
- Highlight the active pen more clearly (a white filled circle behind the colored pen, gray out other pens)
- add a very faint white translucent layer over the map to indicate drawing mode

When the current drawing is finished (as it works now: user finishes a circle or area -- or line), return to "move mode".

**Comment by bhautikpatoliya004** [comment]
@tedbarnett 
- add a very faint white translucent layer over the map to indicate drawing mode
==> I think it's not possible add extra translucent layer on the map as we already adding lines and shapes on the map. If we add extra layer then we can't draw on it. So, we can show toast message when drawing mode ON or any other indication on screen regarding it. Please let me know.

**Comment by tedbarnett** [comment]
The toast message works for now!
