### ISSUE TITLE
Menu Edits

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/MapWalk#24]
Replace "Edit my map" with "Name Current Map"
Replace "See shared maps" with "Shared Maps" (and if opened and there are no shared maps yet: display "Your shared maps will appear here."
Replace "Export KML" with "Share Current Map"
Replace "Import KML" with "Import A Map (or KML)"

And re-order the items as follows:
- Name Current Map
- Share Current Map
- Shared Maps
- Import A Map (or KML)

**Comment by bhautikpatoliya004** [comment]
@tedbarnett Added swipe to Delete feature for shared map.

**Comment by bhautikpatoliya004** [comment]
@tedbarnett Added new menu Item called "Map Overlay"

![Simulator Screenshot - iPhone 15 Pro - 2024-08-05 at 17 13 02](https://github.com/user-attachments/assets/9599f15d-311c-4243-b16b-3b45b3251cba)
