### ISSUE TITLE
Hide minor map icons

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/MapWalk#30]
There are too many map pin icons (eg "McDonalds") cluttering up the map view. Can we hide anything that is not a major item (like hide anything "suggested" like restaurants or bars)?  Worst-case can we hide them all?

![image](https://github.com/user-attachments/assets/fab36546-f566-4b81-b402-f81857a7c150)

**Comment by bhautikpatoliya004** [comment]
@tedbarnett I've hide [.cafe, .bakery, .brewery, .foodMarket, .nightlife, .restaurant, .winery, .hotel, .store] for now. But if we want hide additional "**Point Of Interest Categories**" then we can hide below too.

Airport
Amusement Park
Aquarium
ATM
Bakery
Bank
Beach
Brewery
Cafe
Campground
Car Rental
EV Charger
Fire Station
Fitness Center
Food Market
Gas Station
Hospital
Hotel
Laundry
Library
Marina
Movie Theater
Museum
National Park
Nightlife
Park
Parking
Pharmacy
Police
Post Office
Public Transport
Restaurant
Restroom
School
Stadium
Store
Theater
University
Winery
Zoo

**Comment by tedbarnett** [comment]
Let's also hide the following (from the list above):

Airport
Amusement Park
Aquarium
ATM
Bakery
Bank
Brewery
Cafe
Campground
Car Rental
EV Charger
Fire Station
Fitness Center
Food Market
Gas Station
Hospital
Hotel
Laundry
Marina
Movie Theater
Nightlife
Parking
Pharmacy
Police
Post Office
Public Transport
Restaurant
Restroom
School
Stadium
Store
Theater
Winery
Zoo
