### ISSUE TITLE
Hide all icons, except...

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/MapWalk#34]
Still seeing some unhelpful icons cluttering up the map.

Maybe these are icon categories that did not show up on the list you sent me earlier. For example, "aerial tours".  

![image](https://github.com/user-attachments/assets/ed238483-f564-44c6-b40d-cab5a89b9433)

So...

Can we "hide all" icons except the following:
- park
- nationalPark
- publicTransport

**Comment by tedbarnett** [comment]
Also include
- landmark
- nationalMonument

**Comment by bhautikpatoliya004** [comment]
@tedbarnett There is no Point Of Interest Category available for "landmark" and "nationalMonument". So, we can't hide it.
